[package]
name = "davdr/combat-framework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
jecs = "ukendio/jecs@0.9.0"
jabby = "alicesaidhi/jabby@0.2.0"
replecs = "pepeeltoro41/replecs@0.2.4"
lyra = "paradoxum-games/lyra@0.6.0"